services:
  postgres:
    image: postgres:15
    container_name: postgres_container_lab
    restart: unless-stopped
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: taskdb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  fastapi_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8002:8000"
    networks:
      - backend
    command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"]

  parser_app:
    build:
      context: ./parser_app
      dockerfile: Dockerfile
    container_name: parser_app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8003:8001"
    networks:
      - backend
    command: ["sh", "-c", "sleep 15 && uvicorn app.parser_app:app --host 0.0.0.0 --port 8001"]

  celery_worker:
    build:
      context: ./app
    command: ["sh", "-c", "sleep 20 && celery -A app.celery_app worker --loglevel=info"]
    container_name: celery_worker
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend

  celery_beat:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: celery_beat
    command: ["sh", "-c", "sleep 25 && celery -A app.celery_app beat --loglevel=info"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres:

networks:
  backend: